name = "BlueSkyClient"
uuid = "3ef48bec-961c-4bde-8caa-453a8d838715"
version = "0.1.0"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[workspace]
projects = ["test", "examples"]

[compat]
Dates = "1"
DotEnv = "1.0.0"
FFMPEG = "0.4"
HTTP = "1"
JSON3 = "1.14.3"
julia = "1.12"
