[deps]
BlueSkyClient = "3ef48bec-961c-4bde-8caa-453a8d838715"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
